---
- name: Download and unarchive activemq
  unarchive:
    src:   '{{ amq_download_url }}'
    dest:  '{{ amq_install_dir }}'
    owner: '{{ amq_user }}'
    group: '{{ amq_user }}'
    extra_opts: ['--strip-components=1']
    copy: no
    ignore_errors: yes
